<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="maintenance info.aspx.cs" Inherits="Sociatyacc.maintenance_info" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <style type="text/css">


    .auto-style4 {
        width: 78%;
        height: 450px;
        border: 1px solid #CCFFFF;
        margin-left: 204px;
    }
    .auto-style6 {
        margin-left: 0px;
    }
        .auto-style7 {
            margin-left: 207px;
            margin-right: 91px;
        }
        .auto-style10 {
            width: 245px;
        }
        .auto-style11 {
            width: 77%;
        }
        </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <p style="background-color: #FF99FF">
        <asp:Image ID="Image2" runat="server" Height="304px" ImageUrl="~/images/maitainance charges.jpg" Width="606px" />
    </p>
    <p>
        Information about maintenance charges</p>
    <table class="auto-style4" style="border-style: ridge; border-width: thin; background-color: #99CCFF;">
        <tr>
            <td class="auto-style10" style="border-style: ridge; border-width: thin">
                <asp:Label runat="server" Text="id" ID="Label7"></asp:Label>
            </td>
            <td style="border-style: ridge; border-width: thin" class="auto-style11">
                <asp:TextBox ID="TextBox1" runat="server" autocomplete="off"></asp:TextBox>
            </td>
        </tr>
        <tr>
            <td class="auto-style10" style="border-style: ridge; border-width: thin">
                <asp:Label ID="Label2" runat="server" Text="Society id"></asp:Label>
            </td>
            <td style="border-style: ridge; border-width: thin" class="auto-style11">
                <asp:TextBox ID="TextBox2" runat="server" autocomplete="off"></asp:TextBox>
            </td>
        </tr>
        <tr>
            <td class="auto-style10" style="border-style: ridge; border-width: thin">
                <asp:Label ID="Label8" runat="server" Text="flat area  sqft"></asp:Label>
            </td>
            <td style="border-style: ridge; border-width: thin" class="auto-style11">
                <asp:TextBox ID="TextBox3" runat="server" autocomplete="off"></asp:TextBox>
            </td>
        </tr>
        <tr>
            <td class="auto-style10" style="border-style: ridge; border-width: thin">
                <asp:Label ID="Label3" runat="server" Text="Maintenance charge sqft"></asp:Label>
            </td>
            <td style="border-style: ridge; border-width: thin" class="auto-style11">
                <asp:TextBox ID="TextBox4" runat="server" autocomplete="off"></asp:TextBox>
            </td>
        </tr>
        <tr>
            <td colspan="2" style="border-style: ridge; border-width: thin">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<asp:Button ID="Button2" runat="server" OnClick="Button2_Click" Text="Back" BackColor="#99FF66" Width="149px" />
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <asp:Button ID="Button1" runat="server" BackColor="#66FFFF" CssClass="auto-style6" Text="Submit" Width="163px" OnClick="Button1_Click" />
            </td>
        </tr>
</table>
    <p>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <asp:Button ID="Button3" runat="server" Height="61px" OnClick="Button3_Click" Text="view data" Width="159px" />
&nbsp; &nbsp;</p>
    <p>
        <asp:GridView ID="GridView1" runat="server" AllowPaging="True" AllowSorting="True" CellPadding="4" CssClass="auto-style7" DataSourceID="SqlDataSource1" ForeColor="#333333" GridLines="None" Width="1138px" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" Visible="False">
            <AlternatingRowStyle BackColor="White" />
            <Columns>
                <asp:CommandField ShowSelectButton="True" />
                <asp:BoundField DataField="id" HeaderText="id" SortExpression="id" />
                <asp:BoundField DataField="societyid" HeaderText="societyid" SortExpression="societyid" />
                <asp:BoundField DataField="flat_area_per_sqft" HeaderText="flat_area_per_sqft" SortExpression="flat_area_per_sqft" />
                <asp:BoundField DataField="maintainance_charges_per_sqft" HeaderText="maintainance_charges_per_sqft" SortExpression="maintainance_charges_per_sqft" />
            </Columns>
            <EditRowStyle BackColor="#2461BF" />
            <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
            <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
            <RowStyle BackColor="#EFF3FB" />
            <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
            <SortedAscendingCellStyle BackColor="#F5F7FB" />
            <SortedAscendingHeaderStyle BackColor="#6D95E1" />
            <SortedDescendingCellStyle BackColor="#E9EBEF" />
            <SortedDescendingHeaderStyle BackColor="#4870BE" />
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:SocietyManagementConnectionString8 %>" SelectCommand="SELECT * FROM [maintainance_info]"></asp:SqlDataSource>
    </p>
    <p>
        &nbsp;</p>
    <p>
        &nbsp;</p>
    <p>
    </p>
    <p>
    </p>
    <p>
    </p>
    <p>
    </p>
    <p>
    </p>
</asp:Content>
